# Generated by Django 3.0.7 on 2020-10-14 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soran', models.CharField(max_length=230)),
                ('sorutarihi', models.DateTimeField(auto_now_add=True)),
                ('soru', models.TextField()),
                ('resim', models.ImageField(upload_to='Sorular')),
            ],
        ),
        migrations.CreateModel(
            name='Cevaplar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cevaptarihi', models.DateTimeField(auto_now_add=True)),
                ('cevaplayan', models.CharField(max_length=230)),
                ('cevap', models.TextField()),
                ('resim', models.ImageField(upload_to='Cevaplar')),
                ('soru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Soru')),
            ],
        ),
    ]
