# Generated by Django 3.0.7 on 2020-10-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soru',
            options={'ordering': ['-sorutarihi']},
        ),
        migrations.AddField(
            model_name='soru',
            name='sorukonu',
            field=models.CharField(choices=[('1', 'Ders ile ilgili bir soru'), ('2', 'Danışman hoca ile ilgili bir soru'), ('3', 'UBİS/ALMS ile ilgili bir soru'), ('4', 'Diğer')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='soru',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to='Sorular'),
        ),
    ]
