# Generated by Django 3.0.7 on 2020-10-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20201014_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soru',
            name='sorukonu',
            field=models.CharField(choices=[('Ders ile ilgili bir soru', 'Ders ile ilgili bir soru'), ('Danışman hoca ile ilgili bir soru', 'Danışman hoca ile ilgili bir soru'), ('UBİS/ALMS ile ilgili bir soru', 'UBİS/ALMS ile ilgili bir soru'), ('Diğer', 'Diğer')], default='Ders ile ilgili bir soru', max_length=200),
        ),
    ]
