# Generated by Django 3.0.7 on 2020-10-14 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20201014_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cevaplar',
            old_name='resim',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='soru',
            old_name='resim',
            new_name='image',
        ),
    ]
