# Generated by Django 3.0.7 on 2020-10-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_soru_sorustatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cevaplar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Cevaplar'),
        ),
    ]
