# Generated by Django 3.0.7 on 2020-10-15 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20201015_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cevaplar',
            name='soru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Soru'),
        ),
    ]
